In [1]:
import re
import csv
import pandas as pd
import numpy as np
from ekphrasis.classes.preprocessor import TextPreProcessor
from ekphrasis.dicts.emoticons import emoticons
from ekphrasis.classes.segmenter import Segmenter
from nltk.tokenize import TweetTokenizer
from clean_tweets import clean_tweets
from replace import replace_utf

#### 1) Load in the train and test data

In [2]:
train = pd.DataFrame()

# super inefficient but o well
tweet_id = []
adr_mention = []
tweet_text = []

with open('../train-split.tsv') as f:
    next(f) # skip header
    for line in f:
        line_sep = line.split('\t')

        tweet_id.append(line_sep[0])
        adr_mention.append(line_sep[1])
        tweet_text.append(line_sep[2].strip())

train['tweet_id'] = tweet_id
train['adr_mention'] = adr_mention
train['tweet_text'] = tweet_text

train.head(10)

,tweet_id,adr_mention,tweet_text
0,451439947401031682,0,"""""""well, the way i see it, you can either star..."
1,341735936406732801,0,if i run out of prozac i'ma be pissed man ughhh
2,498679682779611136,0,my friend told me she liked nexplanon more tha...
3,349139925746192384,0,@ferrycorsten @ferrycorstencc #listenerschoice...
4,349038276369330176,0,@sarahtw33ts i'm on 40mg of fluoxetine. and so...
5,418946708329205760,1,"took too much pregabalin in order to sleep, bu..."
6,352241601394913280,0,"how am i still awake after 500 mg seroquel, an..."
7,531156358100709376,0,advair $300 in this country$35 in france. why?...
8,388166024190648320,0,@merangel do you like humira otherwise? good t...
9,515897448083234816,0,@adamwalton ventolin vocals

In [3]:
test = pd.DataFrame()

tweet_id = []
adr_mention = []
tweet_text = []

with open('../test-split.tsv') as f:
    next(f) # skip header
    for line in f:
        line_sep = line.split('\t')

        tweet_id.append(line_sep[0])
        adr_mention.append(line_sep[1])
        tweet_text.append(line_sep[2].strip())

test['tweet_id'] = tweet_id
test['adr_mention'] = adr_mention
test['tweet_text'] = tweet_text

test.head(10)

,tweet_id,adr_mention,tweet_text
0,342260371878449153,0,@joanne__howe so sorry to hear ur under the we...
1,349023751842709504,0,my right hand is so weak i can't even snap my ...
2,539972840117002241,0,sorry i suggested imodium for diarrhea of the ...
3,340450765535576064,0,do you know what is badass ? ciprofloxacin th...
4,529116068196151296,0,i go out walking on lunesta #classicrockdiagnoses
5,525179690429210624,0,@jenhenders yeah thanks will do increased my s...
6,326669870710263808,0,"@selkie1970 no, dosage of the thing that regul..."
7,353636606034444288,0,"@mrsarcticride i take keppra and zonisamide, i..."
8,447146179000664066,0,thank god for ambien and restoril comboðŸ’¤ðŸ’¤ðŸ’¤
9,535076965905358848,0,"""""""he's done some research on buprenorphine th..."

#### 2) Call replace_utf function to remove utf codes 
> Takes in a df and returns a df

In [4]:
train = replace_utf(train)
train.head(10)

,tweet_id,adr_mention,tweet_text
0,451439947401031682,0,"""""""well, the way i see it, you can either star..."
1,341735936406732801,0,if i run out of prozac i'ma be pissed man ughhh
2,498679682779611136,0,my friend told me she liked nexplanon more tha...
3,349139925746192384,0,@ferrycorsten @ferrycorstencc #listenerschoice...
4,349038276369330176,0,@sarahtw33ts i'm on 40mg of fluoxetine. and so...
5,418946708329205760,1,"took too much pregabalin in order to sleep, bu..."
6,352241601394913280,0,"how am i still awake after 500 mg seroquel, an..."
7,531156358100709376,0,advair $300 in this country$35 in france. why?...
8,388166024190648320,0,@merangel do you like humira otherwise? good t...
9,515897448083234816,0,@adamwalton ventolin vocals

In [5]:
test = replace_utf(test)
test.head(10)

,tweet_id,adr_mention,tweet_text
0,342260371878449153,0,@joanne__howe so sorry to hear ur under the we...
1,349023751842709504,0,my right hand is so weak i can't even snap my ...
2,539972840117002241,0,sorry i suggested imodium for diarrhea of the ...
3,340450765535576064,0,do you know what is badass ? ciprofloxacin th...
4,529116068196151296,0,i go out walking on lunesta #classicrockdiagnoses
5,525179690429210624,0,@jenhenders yeah thanks will do increased my s...
6,326669870710263808,0,"@selkie1970 no, dosage of the thing that regul..."
7,353636606034444288,0,"@mrsarcticride i take keppra and zonisamide, i..."
8,447146179000664066,0,thank god for ambien and restoril combo <sleep...
9,535076965905358848,0,"""""""he's done some research on buprenorphine th..."

#### 3) Call clean_tweets to do the rest of the cleaning and processing
> Takes in a df and returns a df

In [6]:
train = clean_tweets(train)
train.head(10)

Reading twitter - 1grams ...
Reading twitter - 2grams ...
Reading twitter - 1grams ...
Reading twitter - 1grams ...
Reading twitter - 2grams ...

,tweet_id,adr_mention,tweet_text
0,451439947401031682,0,""" "" "" well , the way i see it , you can either..."
1,341735936406732801,0,if i run out of prozac i ama be pissed man ugh...
2,498679682779611136,0,my friend told me she liked nexplanon more tha...
3,349139925746192384,0,<user> ferry corsten </user> <user> ferry cors...
4,349038276369330176,0,<user> sarah tw33ts </user> i am on 40mg of fl...
5,418946708329205760,1,"took too much pregabalin in order to sleep , b..."
6,352241601394913280,0,"how am i still awake after 500 mg seroquel , a..."
7,531156358100709376,0,advair <money> in this country <money> in fran...
8,388166024190648320,0,<user> me rangel </user> do you like humira ot...
9,515897448083234816,0,<user> adam walton </user> ventolin vocals

In [7]:
test = clean_tweets(test)
test.head(10)

Reading twitter - 1grams ...
Reading twitter - 2grams ...
Reading twitter - 1grams ...
Reading twitter - 1grams ...
Reading twitter - 2grams ...

,tweet_id,adr_mention,tweet_text
0,342260371878449153,0,<user> joanne __howe </user> so sorry to hear ...
1,349023751842709504,0,my right hand is so weak i can not even snap m...
2,539972840117002241,0,sorry i suggested imodium for diarrhea of the ...
3,340450765535576064,0,do you know what is badass ? ciprofloxacin tha...
4,529116068196151296,0,i go out walking on lunesta <hashtag> classic ...
5,525179690429210624,0,<user> jen hender s </user> yeah thanks will d...
6,326669870710263808,0,"<user> selkie 1970 </user> no , dosage of the ..."
7,353636606034444288,0,<user> mrs arctic ride </user> i take keppra a...
8,447146179000664066,0,thank god for ambien and restoril combo <sleep...
9,535076965905358848,0,""" "" "" he is done some research on buprenorphin..."

In [16]:
export_csv = test.to_csv (r'test_25k.tsv', index = None, header = None, sep = '\t')

In [17]:
export_csv

In [19]:
train = pd.read_csv('train_25k.tsv', delimiter = '\t', header = None)

docs = train[2]
labels = np.array(train[1])

X_train = docs
y_train = labels

In [20]:
test = pd.read_csv('test_25k.tsv', delimiter = '\t', header = None)
docs = test[2]
labels = np.array(test[1])

X_test = docs
y_test = labels

In [22]:
tweets_lst = []
for tweet in X_train:
    tweets_lst.append(tweet)

In [23]:
print(tweets_lst[0:15])

['" " " well , the way i see it , you can either start walking daily or you can start taking januvia daily . it is your choice " " . <repeated> me to dm pt "', 'if i run out of prozac i ama be pissed man ugh <elongated>', 'my friend told me she liked nexplanon more than nuvaring & i was like i remember when you had nuvaring & we might know each other too well .', '<user> ferry corsten </user> <user> ferry corsten </user> cc <hashtag> listeners choice </hashtag> <hashtag> corsten s countdown </hashtag> 313 zehavi & rand - paroxetine ( majera remix ) hopefully not played <laugh>', '<user> sarah tw33ts </user> i am on 40mg of fluoxetine . and soon i will be on ocd medicine i think so life hates me haha .', 'took too much pregabalin in order to sleep , but all that is happened is i am spaced as fuck and lost the use of my hands a bit', 'how am i still awake after 500 mg seroquel , an ambien xr , & two ativan ?', 'advair <money> in this country <money> in france . why ? lobbyists .', '<user> me rangel </user> do you like humira otherwise ? good to have your dad as a remicade reference .', '<user> adam walton </user> ventolin vocals', '" " " bananas contain a natural chemical that can make a person happy - the same chemical found in prozac . " " <user> amy lindsay 87 </user> <hashtag> learn to love them </hashtag> "', 'free 80mg vyvanse from my dads employee for this long day lol <hashtag> thanks </hashtag>', '<user> magpie pants </user> seroquel ? is that some new australian pan-pipe based hip-hop band ? in which case , you should be off in no time !', 'i will take 2.5 mg olanzapine and zopiclone to settle my sleep . i will intervene early , and not leave things until i am euphoric', "got like a month ' s supply of avodart in blister packs for free , having to take each one out to put in the 30 day supply i just got . we <elongated> ."]